# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FY-IMChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # *********************************************** Swift ***********************************************

	pod 'SwiftyJSON'
	pod 'SnapKit'
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'RxTheme'
	pod 'NSObject+Rx'
	pod 'Moya/RxSwift'
	pod 'HandyJSON'
	pod 'ReachabilitySwift'
	pod 'Localize-Swift'
	pod 'Kingfisher'
	pod 'R.swift'
	pod 'WCDB.swift' #本地数据库缓存
	pod 'SwifterSwift'
	pod 'SwiftDate'
  

  # *********************************************** Objective-C ***********************************************

	pod 'UIView+FDCollapsibleConstraints'
	pod 'FDFullscreenPopGesture', '1.1'
	pod 'UITableView+FDTemplateLayoutCell'
	pod 'TZImagePickerController'
	pod 'IQKeyboardManagerSwift'
	pod 'MBProgressHUD'
	pod 'MJRefresh'
	pod 'YBImageBrowser'
	pod 'YBImageBrowser/Video'
	pod 'LookinServer', :configurations => ['Debug'] #UI层级调试
	pod 'IGListKit' #朋友圈列表布局
 	pod 'YYText'
     
end



post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
        end
    end
end


install! 'cocoapods',
          disable_input_output_paths: true,
          generate_multiple_pod_projects: true
