//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.file` struct is generated, and contains static references to 19 files.
  struct file {
    /// Resource file `Emoticons.bundle`.
    static let emoticonsBundle = Rswift.FileResource(bundle: R.hostingBundle, name: "Emoticons", pathExtension: "bundle")
    /// Resource file `Expression.bundle`.
    static let expressionBundle = Rswift.FileResource(bundle: R.hostingBundle, name: "Expression", pathExtension: "bundle")
    /// Resource file `Expression.plist`.
    static let expressionPlist = Rswift.FileResource(bundle: R.hostingBundle, name: "Expression", pathExtension: "plist")
    /// Resource file `HUDAssets.bundle`.
    static let hudAssetsBundle = Rswift.FileResource(bundle: R.hostingBundle, name: "HUDAssets", pathExtension: "bundle")
    /// Resource file `LauguageExcel.xls`.
    static let lauguageExcelXls = Rswift.FileResource(bundle: R.hostingBundle, name: "LauguageExcel", pathExtension: "xls")
    /// Resource file `Light.plist`.
    static let lightPlist = Rswift.FileResource(bundle: R.hostingBundle, name: "Light", pathExtension: "plist")
    /// Resource file `Night.plist`.
    static let nightPlist = Rswift.FileResource(bundle: R.hostingBundle, name: "Night", pathExtension: "plist")
    /// Resource file `code.xls`.
    static let codeXls = Rswift.FileResource(bundle: R.hostingBundle, name: "code", pathExtension: "xls")
    /// Resource file `code_de.plist`.
    static let code_dePlist = Rswift.FileResource(bundle: R.hostingBundle, name: "code_de", pathExtension: "plist")
    /// Resource file `code_en.plist`.
    static let code_enPlist = Rswift.FileResource(bundle: R.hostingBundle, name: "code_en", pathExtension: "plist")
    /// Resource file `code_ja.plist`.
    static let code_jaPlist = Rswift.FileResource(bundle: R.hostingBundle, name: "code_ja", pathExtension: "plist")
    /// Resource file `code_ko.plist`.
    static let code_koPlist = Rswift.FileResource(bundle: R.hostingBundle, name: "code_ko", pathExtension: "plist")
    /// Resource file `code_vi.plist`.
    static let code_viPlist = Rswift.FileResource(bundle: R.hostingBundle, name: "code_vi", pathExtension: "plist")
    /// Resource file `code_zh.plist`.
    static let code_zhPlist = Rswift.FileResource(bundle: R.hostingBundle, name: "code_zh", pathExtension: "plist")
    /// Resource file `exportCode.py`.
    static let exportCodePy = Rswift.FileResource(bundle: R.hostingBundle, name: "exportCode", pathExtension: "py")
    /// Resource file `exportToExcel.py`.
    static let exportToExcelPy = Rswift.FileResource(bundle: R.hostingBundle, name: "exportToExcel", pathExtension: "py")
    /// Resource file `func.sh`.
    static let funcSh = Rswift.FileResource(bundle: R.hostingBundle, name: "func", pathExtension: "sh")
    /// Resource file `importCode.py`.
    static let importCodePy = Rswift.FileResource(bundle: R.hostingBundle, name: "importCode", pathExtension: "py")
    /// Resource file `importLocalizable.py`.
    static let importLocalizablePy = Rswift.FileResource(bundle: R.hostingBundle, name: "importLocalizable", pathExtension: "py")
    
    /// `bundle.url(forResource: "Emoticons", withExtension: "bundle")`
    static func emoticonsBundle(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.emoticonsBundle
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Expression", withExtension: "bundle")`
    static func expressionBundle(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.expressionBundle
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Expression", withExtension: "plist")`
    static func expressionPlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.expressionPlist
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "HUDAssets", withExtension: "bundle")`
    static func hudAssetsBundle(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.hudAssetsBundle
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "LauguageExcel", withExtension: "xls")`
    static func lauguageExcelXls(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.lauguageExcelXls
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Light", withExtension: "plist")`
    static func lightPlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.lightPlist
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Night", withExtension: "plist")`
    static func nightPlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.nightPlist
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "code", withExtension: "xls")`
    static func codeXls(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.codeXls
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "code_de", withExtension: "plist")`
    static func code_dePlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.code_dePlist
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "code_en", withExtension: "plist")`
    static func code_enPlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.code_enPlist
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "code_ja", withExtension: "plist")`
    static func code_jaPlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.code_jaPlist
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "code_ko", withExtension: "plist")`
    static func code_koPlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.code_koPlist
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "code_vi", withExtension: "plist")`
    static func code_viPlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.code_viPlist
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "code_zh", withExtension: "plist")`
    static func code_zhPlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.code_zhPlist
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "exportCode", withExtension: "py")`
    static func exportCodePy(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.exportCodePy
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "exportToExcel", withExtension: "py")`
    static func exportToExcelPy(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.exportToExcelPy
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "func", withExtension: "sh")`
    static func funcSh(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.funcSh
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "importCode", withExtension: "py")`
    static func importCodePy(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.importCodePy
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "importLocalizable", withExtension: "py")`
    static func importLocalizablePy(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.importLocalizablePy
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 58 images.
  struct image {
    /// Image `LaunchImage`.
    static let launchImage = Rswift.ImageResource(bundle: R.hostingBundle, name: "LaunchImage")
    /// Image `MessageVideoDownload`.
    static let messageVideoDownload = Rswift.ImageResource(bundle: R.hostingBundle, name: "MessageVideoDownload")
    /// Image `MessageVideoPlay`.
    static let messageVideoPlay = Rswift.ImageResource(bundle: R.hostingBundle, name: "MessageVideoPlay")
    /// Image `ReceiverImageNodeBorder`.
    static let receiverImageNodeBorder = Rswift.ImageResource(bundle: R.hostingBundle, name: "ReceiverImageNodeBorder")
    /// Image `ToolViewEmotionHL`.
    static let toolViewEmotionHL = Rswift.ImageResource(bundle: R.hostingBundle, name: "ToolViewEmotionHL")
    /// Image `ToolViewEmotion`.
    static let toolViewEmotion = Rswift.ImageResource(bundle: R.hostingBundle, name: "ToolViewEmotion")
    /// Image `ToolViewInputVoiceHL`.
    static let toolViewInputVoiceHL = Rswift.ImageResource(bundle: R.hostingBundle, name: "ToolViewInputVoiceHL")
    /// Image `ToolViewInputVoice`.
    static let toolViewInputVoice = Rswift.ImageResource(bundle: R.hostingBundle, name: "ToolViewInputVoice")
    /// Image `ToolViewKeyboardHL`.
    static let toolViewKeyboardHL = Rswift.ImageResource(bundle: R.hostingBundle, name: "ToolViewKeyboardHL")
    /// Image `ToolViewKeyboard`.
    static let toolViewKeyboard = Rswift.ImageResource(bundle: R.hostingBundle, name: "ToolViewKeyboard")
    /// Image `TypeSelectorBtnHL_Black`.
    static let typeSelectorBtnHL_Black = Rswift.ImageResource(bundle: R.hostingBundle, name: "TypeSelectorBtnHL_Black")
    /// Image `TypeSelectorBtn_Black`.
    static let typeSelectorBtn_Black = Rswift.ImageResource(bundle: R.hostingBundle, name: "TypeSelectorBtn_Black")
    /// Image `beatIcon`.
    static let beatIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "beatIcon")
    /// Image `ic_avatar_placeholder`.
    static let ic_avatar_placeholder = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_avatar_placeholder")
    /// Image `ic_emotion_delete`.
    static let ic_emotion_delete = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_emotion_delete")
    /// Image `ic_group_placeholder`.
    static let ic_group_placeholder = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_group_placeholder")
    /// Image `ic_more_album`.
    static let ic_more_album = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_more_album")
    /// Image `ic_more_camera`.
    static let ic_more_camera = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_more_camera")
    /// Image `ic_more_favorite`.
    static let ic_more_favorite = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_more_favorite")
    /// Image `ic_more_friendcard`.
    static let ic_more_friendcard = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_more_friendcard")
    /// Image `ic_more_location`.
    static let ic_more_location = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_more_location")
    /// Image `ic_more_pay`.
    static let ic_more_pay = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_more_pay")
    /// Image `ic_more_sight`.
    static let ic_more_sight = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_more_sight")
    /// Image `ic_more_video`.
    static let ic_more_video = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_more_video")
    /// Image `ic_more_voice`.
    static let ic_more_voice = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_more_voice")
    /// Image `ic_more_wallet`.
    static let ic_more_wallet = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_more_wallet")
    /// Image `ic_tabbar01_normal`.
    static let ic_tabbar01_normal = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_tabbar01_normal")
    /// Image `ic_tabbar01_selected`.
    static let ic_tabbar01_selected = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_tabbar01_selected")
    /// Image `ic_tabbar02_normal`.
    static let ic_tabbar02_normal = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_tabbar02_normal")
    /// Image `ic_tabbar02_selected`.
    static let ic_tabbar02_selected = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_tabbar02_selected")
    /// Image `ic_tabbar03_normal`.
    static let ic_tabbar03_normal = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_tabbar03_normal")
    /// Image `ic_tabbar03_selected`.
    static let ic_tabbar03_selected = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_tabbar03_selected")
    /// Image `ic_tabbar04_normal`.
    static let ic_tabbar04_normal = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_tabbar04_normal")
    /// Image `ic_tabbar04_selected`.
    static let ic_tabbar04_selected = Rswift.ImageResource(bundle: R.hostingBundle, name: "ic_tabbar04_selected")
    /// Image `icon_arrow_right`.
    static let icon_arrow_right = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon_arrow_right")
    /// Image `icon_emoji_expression`.
    static let icon_emoji_expression = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon_emoji_expression")
    /// Image `icon_more_add`.
    static let icon_more_add = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon_more_add")
    /// Image `icon_nav_back_white`.
    static let icon_nav_back_white = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon_nav_back_white")
    /// Image `icon_qrc_border`.
    static let icon_qrc_border = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon_qrc_border")
    /// Image `icon_qrc_line`.
    static let icon_qrc_line = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon_qrc_line")
    /// Image `message_receiver_background_highlight`.
    static let message_receiver_background_highlight = Rswift.ImageResource(bundle: R.hostingBundle, name: "message_receiver_background_highlight")
    /// Image `message_receiver_background_normal`.
    static let message_receiver_background_normal = Rswift.ImageResource(bundle: R.hostingBundle, name: "message_receiver_background_normal")
    /// Image `message_receiver_background_reversed`.
    static let message_receiver_background_reversed = Rswift.ImageResource(bundle: R.hostingBundle, name: "message_receiver_background_reversed")
    /// Image `message_sender_background_highlight`.
    static let message_sender_background_highlight = Rswift.ImageResource(bundle: R.hostingBundle, name: "message_sender_background_highlight")
    /// Image `message_sender_background_normal`.
    static let message_sender_background_normal = Rswift.ImageResource(bundle: R.hostingBundle, name: "message_sender_background_normal")
    /// Image `message_sender_background_reversed`.
    static let message_sender_background_reversed = Rswift.ImageResource(bundle: R.hostingBundle, name: "message_sender_background_reversed")
    /// Image `message_voice_receiver_normal`.
    static let message_voice_receiver_normal = Rswift.ImageResource(bundle: R.hostingBundle, name: "message_voice_receiver_normal")
    /// Image `message_voice_receiver_playing_1`.
    static let message_voice_receiver_playing_1 = Rswift.ImageResource(bundle: R.hostingBundle, name: "message_voice_receiver_playing_1")
    /// Image `message_voice_receiver_playing_2`.
    static let message_voice_receiver_playing_2 = Rswift.ImageResource(bundle: R.hostingBundle, name: "message_voice_receiver_playing_2")
    /// Image `message_voice_receiver_playing_3`.
    static let message_voice_receiver_playing_3 = Rswift.ImageResource(bundle: R.hostingBundle, name: "message_voice_receiver_playing_3")
    /// Image `message_voice_sender_normal`.
    static let message_voice_sender_normal = Rswift.ImageResource(bundle: R.hostingBundle, name: "message_voice_sender_normal")
    /// Image `message_voice_sender_playing_1`.
    static let message_voice_sender_playing_1 = Rswift.ImageResource(bundle: R.hostingBundle, name: "message_voice_sender_playing_1")
    /// Image `message_voice_sender_playing_2`.
    static let message_voice_sender_playing_2 = Rswift.ImageResource(bundle: R.hostingBundle, name: "message_voice_sender_playing_2")
    /// Image `message_voice_sender_playing_3`.
    static let message_voice_sender_playing_3 = Rswift.ImageResource(bundle: R.hostingBundle, name: "message_voice_sender_playing_3")
    /// Image `play_btn_normal`.
    static let play_btn_normal = Rswift.ImageResource(bundle: R.hostingBundle, name: "play_btn_normal")
    /// Image `play_btn_pressed`.
    static let play_btn_pressed = Rswift.ImageResource(bundle: R.hostingBundle, name: "play_btn_pressed")
    /// Image `player_back_button`.
    static let player_back_button = Rswift.ImageResource(bundle: R.hostingBundle, name: "player_back_button")
    /// Image `player_suspend_button`.
    static let player_suspend_button = Rswift.ImageResource(bundle: R.hostingBundle, name: "player_suspend_button")
    
    /// `UIImage(named: "LaunchImage", bundle: ..., traitCollection: ...)`
    static func launchImage(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.launchImage, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "MessageVideoDownload", bundle: ..., traitCollection: ...)`
    static func messageVideoDownload(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.messageVideoDownload, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "MessageVideoPlay", bundle: ..., traitCollection: ...)`
    static func messageVideoPlay(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.messageVideoPlay, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ReceiverImageNodeBorder", bundle: ..., traitCollection: ...)`
    static func receiverImageNodeBorder(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.receiverImageNodeBorder, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ToolViewEmotion", bundle: ..., traitCollection: ...)`
    static func toolViewEmotion(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.toolViewEmotion, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ToolViewEmotionHL", bundle: ..., traitCollection: ...)`
    static func toolViewEmotionHL(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.toolViewEmotionHL, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ToolViewInputVoice", bundle: ..., traitCollection: ...)`
    static func toolViewInputVoice(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.toolViewInputVoice, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ToolViewInputVoiceHL", bundle: ..., traitCollection: ...)`
    static func toolViewInputVoiceHL(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.toolViewInputVoiceHL, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ToolViewKeyboard", bundle: ..., traitCollection: ...)`
    static func toolViewKeyboard(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.toolViewKeyboard, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ToolViewKeyboardHL", bundle: ..., traitCollection: ...)`
    static func toolViewKeyboardHL(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.toolViewKeyboardHL, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "TypeSelectorBtnHL_Black", bundle: ..., traitCollection: ...)`
    static func typeSelectorBtnHL_Black(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.typeSelectorBtnHL_Black, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "TypeSelectorBtn_Black", bundle: ..., traitCollection: ...)`
    static func typeSelectorBtn_Black(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.typeSelectorBtn_Black, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "beatIcon", bundle: ..., traitCollection: ...)`
    static func beatIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.beatIcon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ic_avatar_placeholder", bundle: ..., traitCollection: ...)`
    static func ic_avatar_placeholder(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_avatar_placeholder, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ic_emotion_delete", bundle: ..., traitCollection: ...)`
    static func ic_emotion_delete(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_emotion_delete, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ic_group_placeholder", bundle: ..., traitCollection: ...)`
    static func ic_group_placeholder(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_group_placeholder, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ic_more_album", bundle: ..., traitCollection: ...)`
    static func ic_more_album(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_more_album, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ic_more_camera", bundle: ..., traitCollection: ...)`
    static func ic_more_camera(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_more_camera, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ic_more_favorite", bundle: ..., traitCollection: ...)`
    static func ic_more_favorite(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_more_favorite, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ic_more_friendcard", bundle: ..., traitCollection: ...)`
    static func ic_more_friendcard(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_more_friendcard, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ic_more_location", bundle: ..., traitCollection: ...)`
    static func ic_more_location(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_more_location, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ic_more_pay", bundle: ..., traitCollection: ...)`
    static func ic_more_pay(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_more_pay, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ic_more_sight", bundle: ..., traitCollection: ...)`
    static func ic_more_sight(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_more_sight, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ic_more_video", bundle: ..., traitCollection: ...)`
    static func ic_more_video(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_more_video, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ic_more_voice", bundle: ..., traitCollection: ...)`
    static func ic_more_voice(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_more_voice, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ic_more_wallet", bundle: ..., traitCollection: ...)`
    static func ic_more_wallet(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_more_wallet, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ic_tabbar01_normal", bundle: ..., traitCollection: ...)`
    static func ic_tabbar01_normal(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_tabbar01_normal, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ic_tabbar01_selected", bundle: ..., traitCollection: ...)`
    static func ic_tabbar01_selected(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_tabbar01_selected, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ic_tabbar02_normal", bundle: ..., traitCollection: ...)`
    static func ic_tabbar02_normal(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_tabbar02_normal, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ic_tabbar02_selected", bundle: ..., traitCollection: ...)`
    static func ic_tabbar02_selected(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_tabbar02_selected, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ic_tabbar03_normal", bundle: ..., traitCollection: ...)`
    static func ic_tabbar03_normal(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_tabbar03_normal, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ic_tabbar03_selected", bundle: ..., traitCollection: ...)`
    static func ic_tabbar03_selected(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_tabbar03_selected, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ic_tabbar04_normal", bundle: ..., traitCollection: ...)`
    static func ic_tabbar04_normal(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_tabbar04_normal, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ic_tabbar04_selected", bundle: ..., traitCollection: ...)`
    static func ic_tabbar04_selected(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ic_tabbar04_selected, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "icon_arrow_right", bundle: ..., traitCollection: ...)`
    static func icon_arrow_right(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icon_arrow_right, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "icon_emoji_expression", bundle: ..., traitCollection: ...)`
    static func icon_emoji_expression(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icon_emoji_expression, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "icon_more_add", bundle: ..., traitCollection: ...)`
    static func icon_more_add(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icon_more_add, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "icon_nav_back_white", bundle: ..., traitCollection: ...)`
    static func icon_nav_back_white(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icon_nav_back_white, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "icon_qrc_border", bundle: ..., traitCollection: ...)`
    static func icon_qrc_border(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icon_qrc_border, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "icon_qrc_line", bundle: ..., traitCollection: ...)`
    static func icon_qrc_line(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icon_qrc_line, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "message_receiver_background_highlight", bundle: ..., traitCollection: ...)`
    static func message_receiver_background_highlight(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.message_receiver_background_highlight, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "message_receiver_background_normal", bundle: ..., traitCollection: ...)`
    static func message_receiver_background_normal(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.message_receiver_background_normal, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "message_receiver_background_reversed", bundle: ..., traitCollection: ...)`
    static func message_receiver_background_reversed(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.message_receiver_background_reversed, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "message_sender_background_highlight", bundle: ..., traitCollection: ...)`
    static func message_sender_background_highlight(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.message_sender_background_highlight, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "message_sender_background_normal", bundle: ..., traitCollection: ...)`
    static func message_sender_background_normal(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.message_sender_background_normal, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "message_sender_background_reversed", bundle: ..., traitCollection: ...)`
    static func message_sender_background_reversed(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.message_sender_background_reversed, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "message_voice_receiver_normal", bundle: ..., traitCollection: ...)`
    static func message_voice_receiver_normal(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.message_voice_receiver_normal, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "message_voice_receiver_playing_1", bundle: ..., traitCollection: ...)`
    static func message_voice_receiver_playing_1(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.message_voice_receiver_playing_1, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "message_voice_receiver_playing_2", bundle: ..., traitCollection: ...)`
    static func message_voice_receiver_playing_2(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.message_voice_receiver_playing_2, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "message_voice_receiver_playing_3", bundle: ..., traitCollection: ...)`
    static func message_voice_receiver_playing_3(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.message_voice_receiver_playing_3, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "message_voice_sender_normal", bundle: ..., traitCollection: ...)`
    static func message_voice_sender_normal(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.message_voice_sender_normal, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "message_voice_sender_playing_1", bundle: ..., traitCollection: ...)`
    static func message_voice_sender_playing_1(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.message_voice_sender_playing_1, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "message_voice_sender_playing_2", bundle: ..., traitCollection: ...)`
    static func message_voice_sender_playing_2(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.message_voice_sender_playing_2, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "message_voice_sender_playing_3", bundle: ..., traitCollection: ...)`
    static func message_voice_sender_playing_3(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.message_voice_sender_playing_3, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "play_btn_normal", bundle: ..., traitCollection: ...)`
    static func play_btn_normal(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.play_btn_normal, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "play_btn_pressed", bundle: ..., traitCollection: ...)`
    static func play_btn_pressed(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.play_btn_pressed, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "player_back_button", bundle: ..., traitCollection: ...)`
    static func player_back_button(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.player_back_button, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "player_suspend_button", bundle: ..., traitCollection: ...)`
    static func player_suspend_button(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.player_suspend_button, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 2 localization tables.
  struct string {
    /// This `R.string.infoPlist` struct is generated, and contains static references to 4 localization keys.
    struct infoPlist {
      /// en translation: App requests your permission to access the photos in the gallery.
      /// 
      /// Locales: en, zh-Hans, ko, vi, de, ja
      static let nsPhotoLibraryAddUsageDescription = Rswift.StringResource(key: "NSPhotoLibraryAddUsageDescription", tableName: "InfoPlist", bundle: R.hostingBundle, locales: ["en", "zh-Hans", "ko", "vi", "de", "ja"], comment: nil)
      /// en translation: App requests your permission to access the photos in the gallery.
      /// 
      /// Locales: en, zh-Hans, ko, vi, de, ja
      static let nsPhotoLibraryUsageDescription = Rswift.StringResource(key: "NSPhotoLibraryUsageDescription", tableName: "InfoPlist", bundle: R.hostingBundle, locales: ["en", "zh-Hans", "ko", "vi", "de", "ja"], comment: nil)
      /// en translation: IMChat
      /// 
      /// Locales: en, zh-Hans, ko, vi, de, ja
      static let cfBundleDisplayName = Rswift.StringResource(key: "CFBundleDisplayName", tableName: "InfoPlist", bundle: R.hostingBundle, locales: ["en", "zh-Hans", "ko", "vi", "de", "ja"], comment: nil)
      /// en translation: To scan the QR code, do you allow using the camera?
      /// 
      /// Locales: en, zh-Hans, ko, vi, de, ja
      static let nsCameraUsageDescription = Rswift.StringResource(key: "NSCameraUsageDescription", tableName: "InfoPlist", bundle: R.hostingBundle, locales: ["en", "zh-Hans", "ko", "vi", "de", "ja"], comment: nil)
      
      /// en translation: App requests your permission to access the photos in the gallery.
      /// 
      /// Locales: en, zh-Hans, ko, vi, de, ja
      static func nsPhotoLibraryAddUsageDescription(_: Void = ()) -> String {
        return NSLocalizedString("NSPhotoLibraryAddUsageDescription", tableName: "InfoPlist", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: App requests your permission to access the photos in the gallery.
      /// 
      /// Locales: en, zh-Hans, ko, vi, de, ja
      static func nsPhotoLibraryUsageDescription(_: Void = ()) -> String {
        return NSLocalizedString("NSPhotoLibraryUsageDescription", tableName: "InfoPlist", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: IMChat
      /// 
      /// Locales: en, zh-Hans, ko, vi, de, ja
      static func cfBundleDisplayName(_: Void = ()) -> String {
        return NSLocalizedString("CFBundleDisplayName", tableName: "InfoPlist", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: To scan the QR code, do you allow using the camera?
      /// 
      /// Locales: en, zh-Hans, ko, vi, de, ja
      static func nsCameraUsageDescription(_: Void = ()) -> String {
        return NSLocalizedString("NSCameraUsageDescription", tableName: "InfoPlist", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    /// This `R.string.localizable` struct is generated, and contains static references to 4 localization keys.
    struct localizable {
      /// en translation: IMChat
      /// 
      /// Locales: en, zh-Hans, ko, vi, de, ja
      static let zero_app_display_name = Rswift.StringResource(key: "zero_app_display_name", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "zh-Hans", "ko", "vi", "de", "ja"], comment: nil)
      /// en translation: Tips
      /// 
      /// Locales: en, zh-Hans, ko, vi, de, ja
      static let app_alert_title_reminder = Rswift.StringResource(key: "app_alert_title_reminder", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "zh-Hans", "ko", "vi", "de", "ja"], comment: nil)
      /// en translation: cancel
      /// 
      /// Locales: en, zh-Hans, ko, vi, de, ja
      static let app_alert_title_cancel = Rswift.StringResource(key: "app_alert_title_cancel", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "zh-Hans", "ko", "vi", "de", "ja"], comment: nil)
      /// en translation: confirm
      /// 
      /// Locales: en, zh-Hans, ko, vi, de, ja
      static let app_alert_title_confirm = Rswift.StringResource(key: "app_alert_title_confirm", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "zh-Hans", "ko", "vi", "de", "ja"], comment: nil)
      
      /// en translation: IMChat
      /// 
      /// Locales: en, zh-Hans, ko, vi, de, ja
      static func zero_app_display_name(_: Void = ()) -> String {
        return NSLocalizedString("zero_app_display_name", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: Tips
      /// 
      /// Locales: en, zh-Hans, ko, vi, de, ja
      static func app_alert_title_reminder(_: Void = ()) -> String {
        return NSLocalizedString("app_alert_title_reminder", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: cancel
      /// 
      /// Locales: en, zh-Hans, ko, vi, de, ja
      static func app_alert_title_cancel(_: Void = ()) -> String {
        return NSLocalizedString("app_alert_title_cancel", bundle: R.hostingBundle, comment: "")
      }
      
      /// en translation: confirm
      /// 
      /// Locales: en, zh-Hans, ko, vi, de, ja
      static func app_alert_title_confirm(_: Void = ()) -> String {
        return NSLocalizedString("app_alert_title_confirm", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try launchScreen.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
